source/ebay/urls.py
from django.urls import path
from ebay.views import AllProductsView, ProductView, ProductCreateView,\
    ProductUpdateView, ProductDeleteView, AddToBasketView, BasketView, \
    InBasketDeleteView, CreateOrder, BasketDeleteOneView

app_name = 'ebay'

urlpatterns = [
    path('', AllProductsView.as_view(), name='all_products'),
    path('add_order/', CreateOrder.as_view(), name='add_order'),
    path('basket/', BasketView.as_view(), name='view_basket'),
    path('basket/<int:pk>/delete', InBasketDeleteView.as_view(), name='delete_in_basket'),
    path('basket/<int:pk>/delete_one', BasketDeleteOneView.as_view(), name='delete_one_in_basket'),
    path('add_product/', ProductCreateView.as_view(), name='add_product'),
    path('product/<int:pk>/', ProductView.as_view(), name='view_product'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('product/<int:pk>/delete', ProductDeleteView.as_view(), name='delete_product'),
    path('product/<int:pk>/add_to_basket', AddToBasketView.as_view(), name='add_to_basket'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ebay.urls')),
    path('accounts/', include('accounts.urls')),
]

source/ebay/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.contrib.sessions.models import Session

CATEGORY_CHOICES = [('food', 'еда'), ('toys', 'игрушки'), ('stationary', 'канцелярия'), ('books', 'книги'),
                    ('other', 'другое')]


class Product(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='наименование')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='описание')
    category = models.CharField(
        max_length=100,
        null=False, blank=False,
        choices=CATEGORY_CHOICES,
        default=CATEGORY_CHOICES[4][0],
        verbose_name='категория')
    remainder = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self):
        return f'{self.name}_(id: {self.id})'

    def get_absolute_url(self):
        return reverse('ebay:view_product', kwargs={'pk': self.pk})

    def get_total_number(self):
        total = Product.objects.all().count()
        return total


class Basket(models.Model):
    product = models.ForeignKey('ebay.Product', related_name='basket', on_delete=models.DO_NOTHING,
                                verbose_name='продукт', null=True, blank=True)
    quantity = models.PositiveIntegerField()
    session_key = models.ForeignKey(Session, on_delete=models.CASCADE, verbose_name='сессия', null=True, blank=True)

    def __str__(self):
        return f'{self.product.name} - {self.quantity}'

    def get_product_total(self):
        return self.quantity * self.product.price


class OrderProduct(models.Model):
    product = models.ForeignKey('ebay.Product', related_name='product_order', on_delete=models.DO_NOTHING,
                                verbose_name='продукт')
    order = models.ForeignKey('ebay.Order', related_name='order_product', on_delete=models.DO_NOTHING,
                              verbose_name='заказы')
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.product} | {self.order}'

    def get_product_total(self):
        return self.quantity * self.product.price


class Order(models.Model):
    product = models.ManyToManyField('ebay.Product', related_name='order', through='ebay.OrderProduct',
                                     through_fields=('order', 'product'), blank=True)
    user = models.ForeignKey(get_user_model(), related_name='orders', on_delete=models.CASCADE,
                             verbose_name='Пользователь', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

source/ebay/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets
from ebay.models import Product, Order


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти",
                             widget=widgets.TextInput(attrs={
                                 'class': 'form-control me-2',
                                 'type': 'search',
                                 'placeholder': 'найти', 'aria-label': 'search'}))


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'category', 'price', 'remainder']
        widgets = {'description': widgets.Textarea(attrs={"cols": 24, "rows": 3, 'class': 'form-control'}),
                   'category': widgets.RadioSelect,
                   'name': widgets.TextInput(attrs={'class': 'form-control'})}
        error_messages = {
            'name': {'required': "Нельзя оставлять название пустым!"},
            'price': {'max_digits': "не больше 7 знаков!"},
            'remainder': {'positive': "Остаток не может быть ниже нуля!"}
        }

    def clean_remainder(self):
        remainder = self.cleaned_data.get('remainder')
        if remainder < 0:
            raise ValidationError('Остаток не может быть ниже нуля!')
        return remainder

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price < 0:
            raise ValidationError('Цена не может быть ниже 0!')
        return price


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = []
        # fields = ['user_name', 'phone', 'address']

source/ebay/views/base_views.py
from django.utils.http import urlencode
from django.views.generic import ListView
from django.db.models import Q


class SearchView(ListView):
    search_form_class = None
    search_form_field = 'search'
    query_name = 'query'
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        if self.form:
            context['form'] = self.form
            if self.search_value:
                context[self.query_name] = urlencode({self.search_form_field: self.search_value})
                context[self.search_form_field] = self.search_value
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(self.get_query())
        return queryset

    def get_search_form(self):
        return self.search_form_class(self.request.GET)

    def get_search_value(self):
        if self.form:
            if self.form.is_valid():
                return self.form.cleaned_data[self.search_form_field]
        return None

    def get_query(self):
        query = Q()
        for field in self.search_fields:
            kwargs = {field: self.search_value}
            query = query | Q(**kwargs)
        return query

source/ebay/views/basket_views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DeleteView

from ebay.models import Basket, Product, Order, OrderProduct
from ebay.forms import OrderForm


class AddToBasketView(View):
    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=kwargs.get('pk'))
        qty = int(request.POST.get('quantity'))

        if not request.session.exists(request.session.session_key):
            request.session.create()

        basket, _ = Basket.objects.get_or_create(product=product, quantity=0, session_key_id=request.session.session_key)

        if product.remainder >= basket.quantity + qty:
            basket.quantity += qty
            basket.save()
        return redirect(self.get_redirect_url())

    def get_redirect_url(self):
        next = self.request.GET.get('next')
        if next:
            return next
        else:
            return reverse('ebay:all_products')


class BasketView(ListView):
    model = Basket
    template_name = 'basket/in_basket.html'
    context_object_name = 'in_basket'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        total = 0
        for element in self.model.objects.all():
            total += element.get_product_total()
        context['total'] = total
        context['form'] = OrderForm()
        return context


class InBasketDeleteView(DeleteView):
    model = Basket
    success_url = reverse_lazy('ebay:view_basket')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)


class BasketDeleteOneView(DeleteView):
    model = Basket
    success_url = reverse_lazy('ebay:view_basket')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.quantity -= 1
        if self.object.quantity < 1:
            self.object.delete()
        else:
            self.object.save()
        return redirect(success_url)


class CreateOrder(View):
    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            order = Order.objects.create(user=request.user)
        else:
            print(request.user)
            order = Order.objects.create(user=None)

        for item in Basket.objects.all():
            OrderProduct.objects.create(product=item.product, quantity=item.quantity, order=order)
            item.product.remainder -= item.quantity
            item.product.save()
            item.delete()

        return redirect('ebay:all_products')

source/ebay/views/busket_views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DeleteView, CreateView

from ebay.models import Basket, Product, Order, OrderProduct
from ebay.forms import OrderForm


class AddToBasketView(View):
    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=kwargs.get('pk'))
        try:
            basket = Basket.objects.get(product=product)
        except Basket.DoesNotExist:
            if product.remainder > 0:
                Basket.objects.create(product=product, quantity=1)
        else:
            if basket.quantity < product.remainder:
                basket.quantity += 1
                basket.save()
        return redirect('all_products')


class BasketView(ListView):
    model = Basket
    template_name = 'basket/in_basket.html'
    context_object_name = 'in_basket'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        total = 0
        for element in self.model.objects.all():
            total += element.get_product_total()
        context['total'] = total
        context['form'] = OrderForm()
        return context


class InBasketDeleteView(DeleteView):
    model = Basket
    success_url = reverse_lazy('view_basket')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)


class CreateOrder(CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('all_products')

    def form_valid(self, form):
        order = form.save()

        for item in Basket.objects.all():
            OrderProduct.objects.create(product=item.product, quantity=item.quantity, order=order)
            item.product.remainder -= item.quantity
            item.product.save()
            item.delete()

        return redirect(self.success_url)

source/ebay/views/product_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView

from ebay.models import Product
from ebay.views.base_views import SearchView
from ebay.forms import ProductForm, SimpleSearchForm

Product.objects.all().order_by("category", "name").filter(remainder__gt=0)


class AllProductsView(SearchView):
    model = Product
    ordering = ['category', 'name']
    template_name = 'products/index.html'
    context_object_name = 'products'
    paginate_by = 5
    paginate_orphans = 1
    search_form_class = SimpleSearchForm
    search_fields = ['name__icontains', 'description__icontains']

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(remainder__gt=0)


class ProductView(DetailView):
    model = Product
    template_name = 'products/product.html'


class ProductCreateView(PermissionRequiredMixin, CreateView):
    model = Product
    template_name = 'products/create_product.html'
    form_class = ProductForm
    permission_required = 'ebay.add_product'
    permission_denied_message = "You don't have rights for this action!"


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    model = Product
    template_name = 'products/update_product.html'
    form_class = ProductForm
    context_object_name = 'product'
    permission_required = 'ebay.add_product'
    permission_denied_message = "You don't have rights for this action!"

    def get_success_url(self):
        return reverse('ebay:view_product', kwargs={'pk': self.object.pk})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = 'products/delete_product.html'
    context_object_name = 'product'
    success_url = reverse_lazy('ebay:all_products')
    permission_required = 'ebay.add_product'
    permission_denied_message = "You don't have rights for this action!"

source/ebay/templates/products/create_product.html
{% extends 'base.html' %}

{% block title %}
    Add product
{% endblock %}

{% block content %}
    <form action="{% url 'ebay:add_product' %}" method="POST" class="mt-5">
        {% include 'partial/form_template.html' with button_text="создать" %}
    </form>
{% endblock %}

source/ebay/templates/products/delete_product.html
{% extends "base.html" %}

{% block title %}Delete {{ product.name }}{% endblock %}

{% block menu %}
    <li class="nav-item"><a class="nav-link" href="{% url 'ebay:add_product' %}">Добавить товар</a></li>
{% endblock %}

{% block content %}
    <br><br><br><h3>Вы точно хотите удалить "{{ product.name }}" из базы?</h3><br><br>
    <form method="POST" action="{% url "ebay:delete_product" product.id %}" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="Да"></p>
        <p><a class="delete_no_link" href="{% url "ebay:all_products" %}">Нет</a></p>
    </form>
{% endblock %}

source/ebay/templates/products/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    All products
{% endblock %}


{% block menu %}
    {% if perms.ebay.add_product %}
        <li class="nav-item"><a class="nav-link" href="{% url 'ebay:add_product' %}">Добавить продукт</a></li>
    {% endif %}
{% endblock %}


{% block search %}
    {% include 'partial/simple_search.html' %}
{% endblock %}


{% block content %}
    <div><br><br><br><h2>Все товары [{{ products.count }}]</h2><br></div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}

<div class="row row-cols-1">
    {% for product in products %}
      <div class="col mt-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">Цена: {{ product.price }}</p>
            <p class="card-text">Категория: {{ product.get_category_display }}</p><br>
            <a href="{{ product.get_absolute_url }}" class="btn btn-info">Подробнее</a>
            {% if perms.ebay.delete_product %}
                <a href="{% url 'ebay:delete_product' product.id %}" class="btn btn-secondary">Удалить</a>
            {% endif %}
            {% if perms.ebay.change_product %}
                <a href="{% url 'ebay:update_product' product.id %}" class="btn btn-secondary">Изменить</a>
            {% endif %}
            {% include 'basket/add_to_basket.html' %}
          </div>
        </div>
      </div>
    {% endfor %}
</div><br>

    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}

{% endblock %}

source/ebay/templates/products/product.html
{% extends 'base.html' %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block menu %}
    {% if perms.ebay.add_product %}
        <li class="nav-item"><a class="nav-link" href="{% url 'ebay:add_product' %}">Добавить</a></li>
    {% endif %}
    {% if perms.ebay.change_product %}
        <li class="nav-item"><a class="nav-link" href="{% url 'ebay:update_product' product.id %}">Изменить</a></li>
    {% endif %}
    {% if perms.ebay.delete_product %}
        <li class="nav-item"><a class="nav-link" href="{% url 'ebay:delete_product' product.id %}">Удалить</a></li>
    {% endif %}
{% endblock %}

{% block content %}
<div class="card w-50 mt-5" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{ product.name }}</h5>
    <p class="card-text">{{ product.description }}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">категерия: {{ product.get_category_display }}</li>
    <li class="list-group-item">цена: {{ product.price }} сом</li>
    <li class="list-group-item">остаток: {{ product.remainder }} шт.</li>
  </ul>
  <div class="card-body">
    {% if perms.ebay.change_product %}
        <a href="{% url 'ebay:update_product' product.id %}" class="btn btn-secondary">Изменить</a>
    {% endif %}
    {% if perms.ebay.delete_product %}
        <a href="{% url 'ebay:delete_product' product.id %}" class="btn btn-secondary">Удалить</a>
    {% endif %}
    {% include 'basket/add_to_basket.html' %}
  </div>
</div>
{% endblock %}

source/ebay/templates/products/update_product.html
{% extends 'base.html' %}

{% block title %}
    Update {{ product.name }}
{% endblock %}

{% block menu %}
    <li class="nav-item"><a class="nav-link" href="{% url 'ebay:add_product' %}">Добавить товар</a></li>
    <li class="nav-item"><a class="nav-link" href="{{ product.get_absolute_url }}">К проекту</a></li>
{% endblock %}

{% block content %}
    <form action="{% url 'ebay:update_product' product.id %}" method="POST" class="mt-5">
        {% include 'partial/form_template.html' with button_text="сохранить" %}
    </form>
{% endblock %}